mqtt:
  enabled: false

cameras:     # No cameras defined, UI wizard should be used
  rattycam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.11:554/Preview_01_main
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/rattycam_2
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args: preset-vaapi
    live:
      streams:
        Stream 1: rattycam_1
        Stream 2: rattycam_2
    record:
      enabled: True
version: 0.17-0
go2rtc:
  streams:
    rattycam_1:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.11:554/Preview_01_main
    rattycam_2:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.11:554/Preview_01_sub
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.11:554/Preview_01_sub
record:
  enabled: True
  continuous:
    days: 7